# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a83e24209f0b7018a457558bc7298ebae231bf83994f9e9f06336b4895be411618f926dd22b6018e14aea98e2657c251e260d871e12497cb39b2cb644734db4d

test:
  secret_key_base: 0595fdfeefc27a94c0ea4f5a7afba7adc2cb5d7cda69695a8ab81c85e5a5af936a9852cbaabdd0d5c6c876cba5b1b75a518735d98aba891aa0b6f1d491fc42fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
